/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigoRouteImport } from './routes/artigo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EbookRouteImport } from './routes/ebook'
import { Route as ImersaoRouteImport } from './routes/imersao'
import { Route as ParaMulheresRouteImport } from './routes/para-mulheres'
import { Route as ParaProfissionaisRouteImport } from './routes/para-profissionais'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigoRoute = ArtigoRouteImport.update({
  id: '/artigo',
  path: '/artigo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookRoute = EbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ImersaoRoute = ImersaoRouteImport.update({
  id: '/imersao',
  path: '/imersao',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaMulheresRoute = ParaMulheresRouteImport.update({
  id: '/para-mulheres',
  path: '/para-mulheres',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaProfissionaisRoute = ParaProfissionaisRouteImport.update({
  id: '/para-profissionais',
  path: '/para-profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigo': typeof ArtigoRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/ebook': typeof EbookRoute
  '/imersao': typeof ImersaoRoute
  '/para-mulheres': typeof ParaMulheresRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigo': typeof ArtigoRoute
  '/contato': typeof ContatoRoute
  '/ebook': typeof EbookRoute
  '/imersao': typeof ImersaoRoute
  '/para-mulheres': typeof ParaMulheresRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigo': typeof ArtigoRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/ebook': typeof EbookRoute
  '/imersao': typeof ImersaoRoute
  '/para-mulheres': typeof ParaMulheresRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigo'
    | '/blog'
    | '/contato'
    | '/ebook'
    | '/imersao'
    | '/para-mulheres'
    | '/para-profissionais'
    | '/sobre'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigo'
    | '/contato'
    | '/ebook'
    | '/imersao'
    | '/para-mulheres'
    | '/para-profissionais'
    | '/sobre'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/artigo'
    | '/blog'
    | '/contato'
    | '/ebook'
    | '/imersao'
    | '/para-mulheres'
    | '/para-profissionais'
    | '/sobre'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigoRoute: typeof ArtigoRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EbookRoute: typeof EbookRoute
  ImersaoRoute: typeof ImersaoRoute
  ParaMulheresRoute: typeof ParaMulheresRoute
  ParaProfissionaisRoute: typeof ParaProfissionaisRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigo': {
      id: '/artigo'
      path: '/artigo'
      fullPath: '/artigo'
      preLoaderRoute: typeof ArtigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook': {
      id: '/ebook'
      path: '/ebook'
      fullPath: '/ebook'
      preLoaderRoute: typeof EbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imersao': {
      id: '/imersao'
      path: '/imersao'
      fullPath: '/imersao'
      preLoaderRoute: typeof ImersaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-mulheres': {
      id: '/para-mulheres'
      path: '/para-mulheres'
      fullPath: '/para-mulheres'
      preLoaderRoute: typeof ParaMulheresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-profissionais': {
      id: '/para-profissionais'
      path: '/para-profissionais'
      fullPath: '/para-profissionais'
      preLoaderRoute: typeof ParaProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigoRoute: ArtigoRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EbookRoute: EbookRoute,
  ImersaoRoute: ImersaoRoute,
  ParaMulheresRoute: ParaMulheresRoute,
  ParaProfissionaisRoute: ParaProfissionaisRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
